# Generated by Django 5.0.2 on 2024-04-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
