# Generated by Django 5.0.2 on 2024-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_user_created_at_user_deleted_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
